## Numpy library

In [51]:
#!conda install numpy
import numpy as np

In [52]:
np.__version__

'1.23.5'

Make Numpy array from Python data structure, i.e list, tuple, ...
Pass the python data structure as parameter to the numpy function

In [53]:
# make a numpy array from python list
my_list = [-1,0,1]
my_list

[-1, 0, 1]

In [54]:
my_list_array = np.array(my_list)
my_list_array,type(my_list_array)

(array([-1,  0,  1]), numpy.ndarray)

In [55]:
# Lets create and cast a list of list to generate 2-D array
my_second_list = [[1,2,3],[4,5,6],[7,8,9]]
my_second_list, type(my_second_list)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [56]:
my_2D_array = np.array(my_second_list)
my_2D_array, type(my_2D_array) # the matrix

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [57]:
# We can use Tuple instead of list as well.
my_tuple = (-1,0,1)
my_tuple_array = np.array(my_tuple)
my_tuple_array,type(my_tuple_array)

(array([-1,  0,  1]), numpy.ndarray)

Numpy built-in funtions:
- arange(start,stop,step,dtype=None), takes 3rd argument as step size
- linspace(), takes 3rd argument as number of point we want
- zeros(), 1-D array gets the number of zeros as argument, 2-D array gets a tuple as argument (number of row, number of column)
- ones(), same as zeros, but return 1
- eye(), return an identity matrix (must be a square matrix), return a 2-D array with ones on the diagonal and zeros elsewhere
- rand(), to generate random numbers, from np.random module, with random samples from a uniform distribution over (0, 1).
- randn(), Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution
- randint(), use randint() to generate random integers from low (inclusive) to high (exclusive)

In [58]:
# range from 0 to 10  similar to range() in Python, upto but not including 10
np.arange(0,10)

# We can give a step (2 in this case)
np.arange(0,11,2)

# We can give the step and dtype
np.arange(0,11,2,dtype=float)    

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [59]:
# start from 1 & end at 15 with 10 evenly spaced points b/w 1 to 15
my_linspace = np.linspace(1,15,10) # between 1 and 15, 10 points with evenly spaced

# Lets find the step size with "retstep" which returns the array and the step size
my_sec_linspace = np.linspace(1,15,9, retstep=True) # determine the step between points

# We can grab array and stepsize separately
print('array is:', my_sec_linspace[0]) # the first index is the array
print('array is:', my_sec_linspace[1]) # the second index is the step


#create another 1-dimensional (1-D) array using linspace() with 30 evenly spaced numbers between 0 and 15
my_next_linspace = np.linspace(0,15,30) # 1-D array
my_next_linspace

array is: [ 1.    2.75  4.5   6.25  8.    9.75 11.5  13.25 15.  ]
array is: 1.75


array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

In [60]:
# create an array with all zeros
np.zeros(3) # 1-D array, the argument is the number of zeros
np.zeros((4,4)) # Creating 2-D array, (no_row, no_col) passing a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
#create an array with all ones
np.ones(3)
np.ones((4,4)) #Creating 2-D array, (no_row, no_col) passing a tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
# eye()
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
# create arrays of random numbers
# with random samples from a uniform distribution over [0, 1)
np.random.rand(3) # 1-D array with three elements

# pass in (no_of_rows, no_of_columns) to rand() to get 2-D array
np.random.rand(2,3) # row, col, note we are not passing a tuple here, each dimension is separate argument

array([[0.95932776, 0.9105445 , 0.68437937],
       [0.74428224, 0.64455148, 0.3668384 ]])

In [64]:
# rand() 1-D array of tow elements
np.random.randn(3)

# 2-D array (4x4), 16 elements
np.random.randn(4,4) # no tuple, each dimension as a separate argument

array([[ 2.4089087 , -0.84796683, -0.24029446,  0.32707533],
       [ 0.73980164,  0.58955271, -1.44603478,  0.06514379],
       [-0.83815576,  0.44541682, -1.86046632, -1.94545271],
       [-1.75992071, -0.83065339, -1.85706178,  1.68500815]])

In [65]:
# randint()
#returns one random int, 1 inclusive, 100 exclusive
np.random.randint(1,100)

#returns ten random int,
np.random.randint(1,100,10)    

array([53,  7, 33, 30, 33, 57,  2, 12, 49, 28])

Array Methods & Attributes:
- reshape(), Returns an array containing the same data with a new shape, it must have same element number of the array
- max(), finding max values
- min(), finding min values
- argmax(), the index locations of max values in array
- argmin(), the index locations of min values in array

Attributes:
- size
- shape, shape returns the shape of your array, how many rows and columns your array have
- dtype

In [66]:
#create 2 arrays using arange() and randint(). 
my_arange = np.arange(16)
my_randint = np.random.randint(0,100,10)

print('Array using arange():', my_arange)
print('Array using randint():', my_randint)

Array using arange(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Array using randint(): [29 95 53 68 15 52 99 97 31 98]


In [67]:
# reshape()
my_arange.reshape(4,4) # any other num will give error, because we have 16 elements in array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
# getting max and min from randint()
my_randint.max()
my_randint.min()

15

In [69]:
# get the index location of max and min values in randit()
my_randint.argmax() # index starts from 0
my_randint.argmin()

4

In [70]:
# shape of array
my_arange.shape

# size of array
my_arange.size

# data type of array
my_arange.dtype

dtype('int32')

In [71]:
# Notice the two sets of brackets in the output, we are using reshape() to convert, 1-D array to 2-D array/matrix
my_arange.reshape(16,1).shape
my_arange.reshape(4,4).shape

(4, 4)

In [72]:
# convert dtype (int32) to (int64)
x = np.array([1,2,3], dtype=np.int64)
x
y = x.astype(np.int32)
y.dtype

dtype('int32')

Indexing & slicing

1-D arrays (vectors)
2-D arrays (matrices)

In [73]:
 # Lets create a simple 1-D NumPy array.
# (we can use arange() as well.)

array_id = np.array([-10, -2, 0, 2, 17, 106,200])

# Getting value at certain index
print('the value at index 0:', array_id[0])

# Using -ve index
print('the value at the index -2:', array_id[-2])

# grab a range
print('our original array is:', array_id)
print('selected slice of the array is:', array_id[0:3])

# use -ve index to grab a range from array
print('the values from 1:-2 index range is:', array_id[1:-2])

# grab values up to index2, and everything from index
print('vaue in array_id upto index 2:', array_id[:2])

print('values in array_id from index 2:', array_id[2:])

# assign new value to a certain index
array_id[0] = -102 # assigning new value to index 0
array_id # the first element changed to -102



the value at index 0: -10
the value at the index -2: 106
our original array is: [-10  -2   0   2  17 106 200]
selected slice of the array is: [-10  -2   0]
the values from 1:-2 index range is: [-2  0  2 17]
vaue in array_id upto index 2: [-10  -2]
values in array_id from index 2: [  0   2  17 106 200]


array([-102,   -2,    0,    2,   17,  106,  200])

# if the index is not exist we get IndexError

In [74]:

#array_id[305]
# to avoid IndexError, we get the size of array using mod operator and pass it to the array
array_id[305 % array_id.size]

print('size of array_id is:', array_id.size)
print('305 % array_id.size is (index location):', 305 % array_id.size)
print('the value at the given index location:', array_id[305 % array_id.size])

size of array_id is: 7
305 % array_id.size is (index location): 4
the value at the given index location: 17


In [75]:
#2-D arrays (matrices)
#create an array with 24 elements using arange() and convert it to 2D matrix using “shape”
array_2d = np.arange(24) # creating 1d array with 24 elements
array_2d.shape = (6,4) # converting to 2d array with 6 rows and 4 cols
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
# to get a complete row (starting from 0) pass the number of row
array_2d[2] # row number 3 (3rd row, index from 0)

# grab the 3rd row using negative index
array_2d[-4] # -0,0 is same index

array([ 8,  9, 10, 11])

General format to get an element from an array is:
- array_2d[row][col]
- array_2d[row,col]

Get a slice of an array:

array_2d[0:2,0:2] ==> array_2d[from_row_0:till_row_2(2 not included), from_col_0:till_col_2(2 not included)]

In [77]:
# get the value at the row=5 and col=2
array_2d[5,2]

#another way
row= 5
col = 2
array_2d[row, col]

# another way
array_2d[5][2]

22

In [78]:
# grab a slice
array_2d[:2,:2] # shape gives (2,2), 4 elements from top left corner
# it is same as array_2d[0:2,0:2]
# from row 0 til row 2 (row 2 is not included),
# from col 0 til col 2 (col 2 is not included)

array_2d[2:4,2:4]

array([[10, 11],
       [14, 15]])

Broadcasting

In [79]:
# Lets create an array using arange()
array_1d = np.arange(0,10) # from 0 to 10 (10 not included)
array_1d

#Take a slice of the array  (0:5) and set it equal to some number, say 500
array_1d[0:5] = 500
array_1d

# Lets create a 2D martix with ones
array_2d = np.ones((4,4))

# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4) # it adds 0,1,2,3 to the elements of the first row
array_2d + 300 # it adds 300 to every elements

array_1d = np.arange(1,4)
array_2d = np.arange(1,4)[:,np.newaxis]
array_2d

array([[1],
       [2],
       [3]])

In [80]:
# Official way of printing is used, format() and len() are used for revisions
print(array_1d)
print('shape of the array is: {}, this is {}-D array'.format(array_1d.shape, len(array_1d.shape)))

# (3,) indicates that this is a one dimensional array (vector)

print(array_2d)
print('shape of the array is: {}, this is {}-D array'.format(array_2d.shape,len(array_2d.shape)))
# (3, 1) indicates that this is a 2-D array (matrix)

[1 2 3]
shape of the array is: (3,), this is 1-D array
[[1]
 [2]
 [3]]
shape of the array is: (3, 1), this is 2-D array


In [81]:
 # Broadcasting arrays
array_1d + array_2d

#np.array([1,2,3]) + np.array([1])
np.ones([3,3]) + np.array([1,2,3])

np.ones([3,1]) + np.arange(1,4)

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [82]:
#fancy indexing
array_2d = np.zeros((5,5))
array_2d[1] = 1 # broadcasting 1 to second row at the index 1
array_2d[2] = 2 # broadcasting 2 to the third row at the index 2
array_2d[3] = 3 # broadcasting 3 to the forth row at the index 3
array_2d[4] = 4 # broadcasting 4 to the fifth row at the index 4
array_2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [83]:
# fancy indexing using for loop
array_2d = np.zeros((5,5))

array_2d.shape[1] # using shape to get the number to run the loop

for i in range(array_2d.shape[1]): #using range() in the loop
    array_2d[i] = i

array_2d # print out the matrix


array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

Fancy indexing allows us to grab any row using its index, let’s grab row 1, 2 and 3. We need to pass in
a list of required rows in square brackets!

In [84]:
array_2d[[1,2,3]]
# We can use any order e.g. row 3, 0 and 4 in this case
array_2d[[3,0,4]]

array([[3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [4., 4., 4., 4., 4.]])

In [85]:
# lets try another matrix for fancy indexing
array_2d = np.arange(24) # 1d array with 24 elements
array_2d.shape = (6,4) # convert 1D array to 2D array
array_2d

# grab list of rows 2,4
array_2d[[2,4]] # need to pass the list of required rows in square brackets

# grab cols
array_2d[:,[3,2]] # for all rows, [3,2] for the 3rd and 2nd cols

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

Boolean masking
- Boolean mask arrays
- Masking operation

In [86]:
# Creating a simple array using arange()
array_1d = np.arange(1,11)

# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array


# A number is even if, number % 2 is "0"
mod_2_mask_id = 0 == array_1d%2
mod_2_mask_id

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [87]:
# filtering out the odds in masking operation
even_values = array_1d[mod_2_mask_id]
print(even_values)

[ 2  4  6  8 10]


In [88]:
# Lets check with our array_2d
array_2d = np.arange(24)
array_2d.shape =(6,4)
mask_mod_2_2d = 0 == array_2d%2 # masking
print(mask_mod_2_2d)
print(array_2d)

 # filtering out the odds in masking operation
print(array_2d[mask_mod_2_2d])

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


Arithmetic operations

In [89]:
# Let's create an array using arange() method
arr = np.arange(0,5)

print(arr)
# Adding two arrays
print(arr + arr)

# Subtracting two arrays
print(arr - arr)

# Multiplication
print(arr*arr)

# Division
print(arr/arr) # we got RuntimeWarning:invalid value encountered in divide # warning and 0/0 is replaced with nan

print(1/arr) # same RuntimeWarning # warning for 1/0, inf

# Power of all the elements in an array
print(arr ** 2)

# Multiplication with scalar
print(arr*2)

[0 1 2 3 4]
[0 2 4 6 8]
[0 0 0 0 0]
[ 0  1  4  9 16]
[nan  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25      ]
[ 0  1  4  9 16]
[0 2 4 6 8]


C:\Users\Nazanin\AppData\Local\Temp\ipykernel_13656\4159363651.py:15: RuntimeWarning: invalid value encountered in divide
  print(arr/arr) # we got RuntimeWarning:invalid value encountered in divide # warning and 0/0 is replaced with nan
C:\Users\Nazanin\AppData\Local\Temp\ipykernel_13656\4159363651.py:17: RuntimeWarning: divide by zero encountered in divide
  print(1/arr) # same RuntimeWarning # warning for 1/0, inf


Universal functions

In [90]:
# Square root
print(np.sqrt(arr))

# max and min values
print('The max element in the array is:',np.max(arr))
print('The min element in the array is:', np.min(arr))

# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
print(np.sin(arr))

# Calculate the exponential (e^) of all elements in the input array
print(np.exp(arr))

# log function
print(np.log(arr)) # warning for inf

# Convert angles from degrees to radians
print(np.deg2rad(arr))

# Convert angles from radians to degrees
print(np.rad2deg(np.deg2rad(arr)))

[0.         1.         1.41421356 1.73205081 2.        ]
The max element in the array is: 4
The min element in the array is: 0
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[0.         0.01745329 0.03490659 0.05235988 0.06981317]
[0. 1. 2. 3. 4.]


C:\Users\Nazanin\AppData\Local\Temp\ipykernel_13656\900519147.py:15: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr)) # warning for inf


## Practice

1. What is the major difference between “Vector” and “Matrix”?

- Vectors are 1 dimension array but Matrix are more than one dimension array


2. How to import NumPy library?

In [91]:
# import numpy as np

3. Convert the given Python list into NumPy array and check its data type.

In [92]:
list_1 = [1,2,3,4,5]
array_1 = np.array(list_1)
array_1,type(array_1)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

4. Generate array [0,1,2,3,4,5] using NumPy built-in function, arange().

In [93]:
array_2 = np.arange(0,6)
array_2

array([0, 1, 2, 3, 4, 5])

5. Generate an array of "5" zeros

In [94]:
array_3 = np.zeros(5)
array_3

array([0., 0., 0., 0., 0.])

6. Generate the following matrix (3,4) zeros

In [95]:
matrix_1 = np.zeros((3,4))
matrix_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

7. Generate [1.,1.,1.,1.,1.] using NumPy built-in function?


In [96]:
array_4 = np.ones(5)
array_4

array([1., 1., 1., 1., 1.])

8. Generate an array of “5” tens.

In [97]:
array_5 = np.ones(5) * 10
array_5

array([10., 10., 10., 10., 10.])

9. Use arange() to generate an array of even numbers between 50 and 100. 50 and 100 are not included

In [98]:
array_6 = np.arange(52,100,2)
array_6

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

10. Generate an array of 10 linearly spaced points between 0 and 1. Output step size as well?

In [99]:
# np.linspace(0,1,10), np.linspace(0,1,10)[1]
array_7 = np.linspace(0,1,10, retstep=True)
print('the array between 0,1 with 10 points:',array_7[0])
print('the step size is:', array_7[1])

the array between 0,1 with 10 points: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
the step size is: 0.1111111111111111


11. Perform the following tasks:

- Generate a vector array of 25 numbers using arange().
- Write a code to convert the vector array into 2-D matrix using reshape.
- Can we use shape instead of reshape as well? No

In [100]:
# generating array vector
array_8 = np.arange(25)
print(array_8)

# convert vector array into 2D matrix using reshape
matrix_2 = array_8.reshape((5,5))
#print(matrix_2)

# shape vs reshape
array_9 = np.arange(25)
array_9.shape = (5,5)
array_9


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

12. Please generate the following matrix. (5,5) (0.1,2.5)

In [101]:
array_10 = np.arange(0,2.6,0.1,dtype=float)[1:] 
array_10.shape = (5,5)


np.arange(1,26).reshape(5,5) / 10

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

13. Write a code to generate the output below, use “linspace()” and “print()”.

In [102]:
array_11 = np.linspace(0,24,25) # having this argument ,retstep=True, make it as tuple
print(array_11.reshape(5,5)) # making the matrix
print('Step size is:', np.linspace(0,24,25)[1])

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
Step size is: 1.0


14. What is the main difference between linspace() and arange()?
- arange() takes 3rd argument as step size.
- linspace() take 3rd argument as no of point we want

15. How to generate a single random number using NumPy built-in function?


In [103]:
np.random.rand()

0.9729530506257676

16. Write a code to generate a 7x5 matrix of 35 random numbers? Notice, there are no ( ) in the output
matrix!

In [104]:
print(np.random.rand(35).reshape(7,5))
# using print() will remove the () form the output

# OR print(np.random.rand(7,5))

[[0.58122771 0.65533569 0.03520981 0.70819337 0.05026575]
 [0.36678063 0.23664701 0.19891849 0.25706153 0.12551863]
 [0.06667517 0.97216068 0.49933747 0.28886937 0.41284579]
 [0.50127504 0.02342139 0.32561111 0.68256193 0.76040336]
 [0.30804584 0.3238113  0.2684944  0.24851697 0.31140886]
 [0.27969297 0.97141444 0.97210368 0.67951087 0.90067281]
 [0.38114112 0.12653769 0.19871235 0.46510301 0.26939044]]


17. Generate the following matrix using NumPy’s built-in method for identity matrix. (5,5)


In [105]:
np.eye(5,5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

18. Generate the follow matrix “array_2d” and replicate the provided outputs.


In [106]:

# generate array_2d
array_2d = np.arange(0,30)
print(array_2d)

# convert it into matrix
matrix_3 = array_2d.reshape(6,5) 
print(matrix_3)

# OR array_2d= np.arange(30).reshape(6,5)


# grab a slice of the matrix
matrix_3[3:,2:]

# grab an element from the matrix
matrix_3[5,4]

# grba another slice
print(matrix_3[:3, 1:2]) # array_2d[:3,1:3] for col 1 and 2

# grab a row
print(matrix_3[2, :]) #array_2d[2:3,:]

# grab two rows
print(matrix_3[2:4,:])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 1]
 [ 6]
 [11]]
[10 11 12 13 14]
[[10 11 12 13 14]
 [15 16 17 18 19]]


19. Can you calculate the sum of all the numbers in array_2d?


In [107]:
sum_of_array = array_2d.sum()
sum_of_array

435

20. Calculate sum of all the rows and columns in array_2d.


In [108]:
print('The row sum is:', matrix_3.sum(axis = 1))
print('The col sum is:', matrix_3.sum(axis = 0))

The row sum is: [ 10  35  60  85 110 135]
The col sum is: [75 81 87 93 99]


21. Calculate the standard deviation of the values in array_2d.


In [109]:
std_of_array = array_2d.std()
std_of_array

8.65544144839919

22. Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.


In [110]:
# Lets check with our array_2d
mask_mod_3 = 0 != array_2d%3 # creating mask for numbers not divided by 3
array_2d[mask_mod_3]
 # filtering out the odds in masking operation


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])